## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *
from eudplib.epscript.helper import _RELIMP, _IGVA, _CGFW, _ARR, _VARR, _SRET, _SV, _ATTW, _ARRW, _ATTC, _ARRC, _L2V, _LVAR, _LSH
# (Line 1) import py_random;
import random
# (Line 2) import py_itertools;
import itertools
# (Line 3) import collections.deque;
from collections import deque
# (Line 4) function test_write() {
@EUDFunc
def f_test_write():
    # (Line 5) const ret = py_list();
    ret = list()
    # (Line 7) const u32 = py_eval("lambda: random.randint(1, 0xFFFFFFFF)");
    u32 = eval("lambda: random.randint(1, 0xFFFFFFFF)")
    # (Line 8) const shift = py_eval("lambda: random.randint(0, 31)");
    shift = eval("lambda: random.randint(0, 31)")
    # (Line 10) const num = u32(), u32(), u32(), u32(), u32(), u32(),
    # (Line 11) shift(), shift(), u32(), u32(), u32();
    num = u32(), u32(), u32(), u32(), u32(), u32(), shift(), shift(), u32(), u32(), u32()
    # (Line 12) const numV = EUDArray(num);
    numV = EUDArray(num)
    # (Line 13) const numS = num, numV;
    numS = num, numV
    # (Line 14) setcurpl(getuserplayerid());
    f_setcurpl(f_getuserplayerid())
    # (Line 15) const dbg = StringBuffer(3000);
    dbg = StringBuffer(3000)
    # (Line 16) dbg.insert(0);
    dbg.insert(0)
    # (Line 17) foreach(vals : numS) {
    for vals in numS:
        # (Line 18) var expect = vals[0];
        expect = _LVAR([vals[0]])
        # (Line 19) expect += vals[1];
        expect.__iadd__(vals[1])
        # (Line 20) expect -= vals[2];
        expect.__isub__(vals[2])
        # (Line 21) dbg.appendf("\n\x07{:x}\x02 *= {:x}", expect, vals[3],);
        dbg.appendf("\n\x07{:x}\x02 *= {:x}", expect, vals[3])
        # (Line 22) expect *= vals[3];
        expect.__imul__(vals[3])
        # (Line 23) var temp = expect;
        temp = _LVAR([expect])
        # (Line 24) dbg.appendf(" -> \x07{:x}\x02 /= {:x}", expect, vals[4],);
        dbg.appendf(" -> \x07{:x}\x02 /= {:x}", expect, vals[4])
        # (Line 25) expect /= vals[4];
        expect.__ifloordiv__(vals[4])
        # (Line 26) temp += expect;
        temp.__iadd__(expect)
        # (Line 27) dbg.appendf(" -> \x07{}\x02 %= {:x}", expect, vals[5],);
        dbg.appendf(" -> \x07{}\x02 %= {:x}", expect, vals[5])
        # (Line 28) expect %= vals[5];
        expect.__imod__(vals[5])
        # (Line 29) temp += expect;
        temp.__iadd__(expect)
        # (Line 30) dbg.appendf(" -> \x07{}\x02 <<= {}", expect, vals[6],);
        dbg.appendf(" -> \x07{}\x02 <<= {}", expect, vals[6])
        # (Line 31) expect <<= vals[6];
        expect.__ilshift__(vals[6])
        # (Line 32) temp += expect;
        temp.__iadd__(expect)
        # (Line 33) dbg.appendf(" -> \x07{:x}\x02 >>= {}", expect, vals[7],);
        dbg.appendf(" -> \x07{:x}\x02 >>= {}", expect, vals[7])
        # (Line 34) expect >>= vals[7];
        expect.__irshift__(vals[7])
        # (Line 35) temp += expect;
        temp.__iadd__(expect)
        # (Line 38) dbg.appendf(" -> \x07{}\x02 &= {:x}", expect, vals[8]);
        dbg.appendf(" -> \x07{}\x02 &= {:x}", expect, vals[8])
        # (Line 39) expect &= vals[8];
        expect.__iand__(vals[8])
        # (Line 40) temp += expect;
        temp.__iadd__(expect)
        # (Line 41) dbg.appendf(" -> \x07{}\x02 |= {:x}", expect, vals[9]);
        dbg.appendf(" -> \x07{}\x02 |= {:x}", expect, vals[9])
        # (Line 42) expect |= vals[9];
        expect.__ior__(vals[9])
        # (Line 43) temp += expect;
        temp.__iadd__(expect)
        # (Line 44) dbg.appendf(" -> \x07{:x}", expect);
        dbg.appendf(" -> \x07{:x}", expect)
        # (Line 45) expect ^= vals[10];
        expect.__ixor__(vals[10])
        # (Line 46) temp += expect;
        temp.__iadd__(expect)
        # (Line 47) ret.append(temp);
        ret.append(temp)
        # (Line 48) }
        # (Line 49) const pvar, arr = PVariable(), EUDArray(8);

    pvar, arr = List2Assignable([PVariable(), EUDArray(8)])
    # (Line 50) var v1, v2 = pvar, arr;
    v1, v2 = _LVAR([pvar, arr])
    # (Line 51) const pvarV, arrV = PVariable.cast(v1), EUDArray.cast(v2);
    pvarV, arrV = List2Assignable([PVariable.cast(v1), EUDArray.cast(v2)])
    # (Line 53) const index = py_eval("random.randint(0, 7)");
    index = eval("random.randint(0, 7)")
    # (Line 54) var indexV = index;
    indexV = _LVAR([index])
    # (Line 56) foreach(arr, i, vals : py_eval("itertools.product(\
    # (Line 58) )")) {
    for arr_1, i, vals in eval("itertools.product(        (pvar, arr, pvarV, arrV), (index, indexV), (num, numV)    )"):
        # (Line 59) arr[i] = vals[0];
        _ARRW(arr_1, i) << (vals[0])
        # (Line 60) arr[i] += vals[1];
        _ARRW(arr_1, i).__iadd__(vals[1])
        # (Line 61) arr[i] -= vals[2];
        _ARRW(arr_1, i).__isub__(vals[2])
        # (Line 62) arr[i] *= vals[3];
        _ARRW(arr_1, i).__imul__(vals[3])
        # (Line 63) var temp = arr[i];
        temp = _LVAR([arr_1[i]])
        # (Line 64) arr[i] /= vals[4];
        _ARRW(arr_1, i).__ifloordiv__(vals[4])
        # (Line 65) temp += arr[i];
        temp.__iadd__(arr_1[i])
        # (Line 66) arr[i] %= vals[5];
        _ARRW(arr_1, i).__imod__(vals[5])
        # (Line 67) temp += arr[i];
        temp.__iadd__(arr_1[i])
        # (Line 68) arr[i] <<= vals[6];
        _ARRW(arr_1, i).__ilshift__(vals[6])
        # (Line 69) temp += arr[i];
        temp.__iadd__(arr_1[i])
        # (Line 70) arr[i] >>= vals[7];
        _ARRW(arr_1, i).__irshift__(vals[7])
        # (Line 71) temp += arr[i];
        temp.__iadd__(arr_1[i])
        # (Line 74) arr[i] &= vals[8];
        _ARRW(arr_1, i).__iand__(vals[8])
        # (Line 75) temp += arr[i];
        temp.__iadd__(arr_1[i])
        # (Line 76) arr[i] |= vals[9];
        _ARRW(arr_1, i).__ior__(vals[9])
        # (Line 77) temp += arr[i];
        temp.__iadd__(arr_1[i])
        # (Line 78) arr[i] ^= vals[10];
        _ARRW(arr_1, i).__ixor__(vals[10])
        # (Line 79) temp += arr[i];
        temp.__iadd__(arr_1[i])
        # (Line 80) ret.append(temp);
        ret.append(temp)
        # (Line 81) }
        # (Line 82) dbg.Display();

    dbg.Display()
    # (Line 84) return List2Assignable(ret);
    EUDReturn(List2Assignable(ret))
    # (Line 85) }
    # (Line 86) function test_compare() {

@EUDFunc
def f_test_compare():
    # (Line 87) const ret = py_list();
    ret = list()
    # (Line 88) const u32 = py_eval("lambda: random.randint(1, 0xFFFFFFFF)");
    u32 = eval("lambda: random.randint(1, 0xFFFFFFFF)")
    # (Line 90) const num = u32(), u32(), u32(), u32(), u32(), u32(), u32();
    num = u32(), u32(), u32(), u32(), u32(), u32(), u32()
    # (Line 91) const numV = EUDArray(num);
    numV = EUDArray(num)
    # (Line 93) const pvar, arr = PVariable(), EUDArray(8);
    pvar, arr = List2Assignable([PVariable(), EUDArray(8)])
    # (Line 94) var v1, v2 = pvar, arr;
    v1, v2 = _LVAR([pvar, arr])
    # (Line 95) const pvarV, arrV = PVariable.cast(v1), EUDArray.cast(v2);
    pvarV, arrV = List2Assignable([PVariable.cast(v1), EUDArray.cast(v2)])
    # (Line 97) const index = py_eval("random.randint(0, 7)");
    index = eval("random.randint(0, 7)")
    # (Line 98) var indexV = index;
    indexV = _LVAR([index])
    # (Line 100) foreach(arr, i, vals : py_eval("itertools.product(\
    # (Line 102) )")) {
    for arr_1, i, vals in eval("itertools.product(        (pvar, arr, pvarV, arrV), (index, indexV), (num, numV)    )"):
        # (Line 103) var temp = 0;
        temp = _LVAR([0])
        # (Line 104) arr[i] = vals[0];
        _ARRW(arr_1, i) << (vals[0])
        # (Line 105) if (arr[i] == vals[1]) temp += 1 << 1;
        if EUDIf()(_ARRC(arr_1, i) == vals[1]):
            temp.__iadd__(_LSH(1,1))
            # (Line 106) if (arr[i] != vals[2]) temp += 1 << 2;
        EUDEndIf()
        if EUDIf()(_ARRC(arr_1, i) == vals[2], neg=True):
            temp.__iadd__(_LSH(1,2))
            # (Line 107) if (arr[i] >= vals[3]) temp += 1 << 3;
        EUDEndIf()
        if EUDIf()(_ARRC(arr_1, i) >= vals[3]):
            temp.__iadd__(_LSH(1,3))
            # (Line 108) if (arr[i] <= vals[4]) temp += 1 << 4;
        EUDEndIf()
        if EUDIf()(_ARRC(arr_1, i) <= vals[4]):
            temp.__iadd__(_LSH(1,4))
            # (Line 109) if (arr[i] > vals[5]) temp += 1 << 5;
        EUDEndIf()
        if EUDIf()(_ARRC(arr_1, i) <= vals[5], neg=True):
            temp.__iadd__(_LSH(1,5))
            # (Line 110) if (arr[i] < vals[6]) temp += 1 << 6;
        EUDEndIf()
        if EUDIf()(_ARRC(arr_1, i) >= vals[6], neg=True):
            temp.__iadd__(_LSH(1,6))
            # (Line 111) ret.append(temp);
        EUDEndIf()
        ret.append(temp)
        # (Line 112) }
        # (Line 114) return List2Assignable(ret);

    EUDReturn(List2Assignable(ret))
    # (Line 115) }
    # (Line 116) const q8 = EUDQueue(8)();

q8 = _CGFW(lambda: [EUDQueue(8)()], 1)[0]
# (Line 117) function test_queue() {
@EUDFunc
def f_test_queue():
    # (Line 118) var ret = 0;
    ret = _LVAR([0])
    # (Line 119) ret += q8.empty() ? 0b1 : 0;  // ret = 1
    ret.__iadd__(EUDTernary(q8.empty())(0b1)(0))
    # (Line 120) q8.append(1);
    q8.append(1)
    # (Line 121) q8.append(EUDVariable(2));
    q8.append(EUDVariable(2))
    # (Line 122) ret += 1 << q8.popleft();  // pop 1, ret = 3
    ret.__iadd__(_LSH(1,q8.popleft()))
    # (Line 123) q8.append(EUDVariable(3));
    q8.append(EUDVariable(3))
    # (Line 124) ret += q8.empty() ? 0x80000000 : 0;
    ret.__iadd__(EUDTernary(q8.empty())(0x80000000)(0))
    # (Line 125) ret += q8.popleft() == 2 ? 0b100 : 0;  // pop 2, ret = 7
    ret.__iadd__(EUDTernary(q8.popleft() == 2)(0b100)(0))
    # (Line 126) ret += q8.popleft() == 3 ? 0b1000 : 0;  // pop 3, ret = 15
    ret.__iadd__(EUDTernary(q8.popleft() == 3)(0b1000)(0))
    # (Line 127) ret += q8.empty() ? 0b10000 : 0;  // ret = 31
    ret.__iadd__(EUDTernary(q8.empty())(0b10000)(0))
    # (Line 128) return ret;
    EUDReturn(ret)
    # (Line 129) }
    # (Line 130) const methods = py_eval('{\

# (Line 133) }');
methods = _CGFW(lambda: [eval('{    "append": "a",   "appendleft": "aL",    "pop":    "p",   "popleft":    "pL"}')], 1)[0]
# (Line 134) const DequeCases = py_eval('random.sample(sorted(methods.getValue()), 27, counts=[9, 9, 9, 9])');
DequeCases = _CGFW(lambda: [eval('random.sample(sorted(methods.getValue()), 27, counts=[9, 9, 9, 9])')], 1)[0]
# (Line 135) const DequeTest = py_eval("''.join(methods[name] for name in DequeCases)");
DequeTest = _CGFW(lambda: [eval("''.join(methods[name] for name in DequeCases)")], 1)[0]
# (Line 136) const dq = EUDDeque(7)();
dq = _CGFW(lambda: [EUDDeque(7)()], 1)[0]
# (Line 137) function test_deque() {
@EUDFunc
def f_test_deque():
    # (Line 138) const ret = py_list();
    ret = list()
    # (Line 139) var pushes = 1;
    pushes = _LVAR([1])
    # (Line 140) const a = function () { dq.append(pushes); pushes++; };
    @EUDFunc
    def _lambda1():
        dq.append(pushes)
        pushes.__iadd__(1)

    a = _lambda1
    # (Line 141) const aL = function () { dq.appendleft(pushes); pushes++; };
    @EUDFunc
    def _lambda2():
        dq.appendleft(pushes)
        pushes.__iadd__(1)

    aL = _lambda2
    # (Line 142) const _p = function() { if (dq.empty()) return 0; else return dq.pop(); };
    @EUDFunc
    def _lambda3():
        if EUDIf()(dq.empty()):
            EUDReturn(0)
        if EUDElse()():
            EUDReturn(dq.pop())
        EUDEndIf()

    _p = _lambda3
    # (Line 143) const _pL = function() { if (dq.empty()) return 0; else return dq.popleft(); };
    @EUDFunc
    def _lambda4():
        if EUDIf()(dq.empty()):
            EUDReturn(0)
        if EUDElse()():
            EUDReturn(dq.popleft())
        EUDEndIf()

    _pL = _lambda4
    # (Line 144) const p = py_eval('lambda s=ret, f=_p: s.append(f())');
    p = eval('lambda s=ret, f=_p: s.append(f())')
    # (Line 145) const pL = py_eval('lambda s=ret, f=_pL: s.append(f())');
    pL = eval('lambda s=ret, f=_pL: s.append(f())')
    # (Line 146) const methodMap = py_eval('{\
    # (Line 149) }');
    methodMap = eval('{        "append":     a,    "pop":     p,        "appendleft": aL,   "popleft": pL,    }')
    # (Line 150) foreach(method : DequeCases) { methodMap[method](); }
    for method in DequeCases:
        methodMap[method]()
        # (Line 151) var sum = dq.length;  // TODO: implement __iter__

    sum = _LVAR([dq.length])
    # (Line 152) while (!dq.empty()) {
    if EUDWhile()(dq.empty(), neg=True):
        # (Line 153) sum += dq.pop();
        sum.__iadd__(dq.pop())
        # (Line 154) }
        # (Line 155) ret.append(sum);
    EUDEndWhile()
    ret.append(sum)
    # (Line 156) return List2Assignable(ret);
    EUDReturn(List2Assignable(ret))
    # (Line 157) }
