## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *
from eudplib.core.eudfunc import EUDTraceLog, EUDTracedFunc, EUDTracedTypedFunc, EUDTracedMethod, EUDTracedTypedMethod
from eudplib.epscript.helper import _RELIMP, _TYGV, _TYSV, _TYLV, _CGFW, _ARR, _VARR, _SRET, _SV, _ATTW, _ARRW, _ATTC, _ARRC, _L2V, _LSH, _ALL
# (Line 1) function switch_test(): EUDArray {
@EUDTypedFunc([], [EUDArray])
def f_switch_test():
    # (Line 2) const ret = EUDArray(6);
    ret = EUDArray(6)
    # (Line 3) static var x = 1234;
    x = _TYSV([None], [1234])
    # (Line 4) py_print("XX", x);
    print("XX", x)
    # (Line 5) static var s = EPD(x.getValueAddr());
    s = _TYSV([None], [EPD(x.getValueAddr())])
    # (Line 6) py_print("XXSS", x, s);
    print("XXSS", x, s)
    # (Line 8) switch(x) {}
    EUDSwitch(x)
    # (Line 9) epdswitch(s) {}
    EUDEndSwitch()
    EPDSwitch(s)
    # (Line 12) epdswitch (s, 240) {
    EUDEndSwitch()
    EPDSwitch(s, 240)
    # (Line 13) case 96:
    _t1 = EUDSwitchCase()
    # (Line 14) x += 1;
    if _t1(96):
        x.__iadd__(1)
        # (Line 15) break;
        EUDBreak()
        # (Line 16) case 160:
    _t2 = EUDSwitchCase()
    # (Line 17) x += 3;
    if _t2(160):
        x.__iadd__(3)
        # (Line 18) break;
        EUDBreak()
        # (Line 19) case 208:  // OK
    _t3 = EUDSwitchCase()
    # (Line 20) x += 5;
    if _t3(208):
        x.__iadd__(5)
        # (Line 21) break;
        EUDBreak()
        # (Line 22) default:
    # (Line 23) x = 0;
    if EUDSwitchDefault()():
        x << (0)
        # (Line 24) }
    # (Line 25) ret[0] = x;  // 1239
    EUDEndSwitch()
    _ARRW(ret, 0) << (x)
    # (Line 28) epdswitch (s, 56) {
    EPDSwitch(s, 56)
    # (Line 29) case 8:
    _t4 = EUDSwitchCase()
    # (Line 30) x += 2;
    if _t4(8):
        x.__iadd__(2)
        # (Line 31) break;
        EUDBreak()
        # (Line 32) case 16:  // OK
    _t5 = EUDSwitchCase()
    # (Line 33) x += 4;
    if _t5(16):
        x.__iadd__(4)
        # (Line 34) break;
        EUDBreak()
        # (Line 35) case 24:
    _t6 = EUDSwitchCase()
    # (Line 36) x += 6;
    if _t6(24):
        x.__iadd__(6)
        # (Line 37) break;
        EUDBreak()
        # (Line 38) case 32:
    _t7 = EUDSwitchCase()
    # (Line 39) x += 8;
    if _t7(32):
        x.__iadd__(8)
        # (Line 40) break;
        EUDBreak()
        # (Line 41) default:
    # (Line 42) x = 0;
    if EUDSwitchDefault()():
        x << (0)
        # (Line 43) }
    # (Line 44) ret[1] = x;  // 1243
    EUDEndSwitch()
    _ARRW(ret, 1) << (x)
    # (Line 47) switch (x, 432) {
    EUDSwitch(x, 432)
    # (Line 48) case 16:
    _t8 = EUDSwitchCase()
    # (Line 49) case 144:  // OK
    if _t8(16):
        pass
    _t9 = EUDSwitchCase()
    # (Line 50) x += 3;
    if _t9(144):
        x.__iadd__(3)
        # (Line 51) break;
        EUDBreak()
        # (Line 52) default:
    # (Line 53) x = 0;
    if EUDSwitchDefault()():
        x << (0)
        # (Line 54) }
    # (Line 55) ret[2] = x;  // 1246
    EUDEndSwitch()
    _ARRW(ret, 2) << (x)
    # (Line 58) switch (x, 211) {
    EUDSwitch(x, 211)
    # (Line 59) case 208:
    _t10 = EUDSwitchCase()
    # (Line 60) x += 5;
    if _t10(208):
        x.__iadd__(5)
        # (Line 61) break;
        EUDBreak()
        # (Line 62) case 210:
    _t11 = EUDSwitchCase()
    # (Line 63) x += 10;
    if _t11(210):
        x.__iadd__(10)
        # (Line 64) break;
        EUDBreak()
        # (Line 65) case 211:
    _t12 = EUDSwitchCase()
    # (Line 66) x += 15;
    if _t12(211):
        x.__iadd__(15)
        # (Line 67) break;
        EUDBreak()
        # (Line 68) default:
    # (Line 69) x = 0;
    if EUDSwitchDefault()():
        x << (0)
        # (Line 70) }
    # (Line 71) ret[3] = x;  // 1256
    EUDEndSwitch()
    _ARRW(ret, 3) << (x)
    # (Line 74) switch (x, 373) {
    EUDSwitch(x, 373)
    # (Line 75) case 96:  // OK
    _t13 = EUDSwitchCase()
    # (Line 76) x += 2;
    if _t13(96):
        x.__iadd__(2)
        # (Line 77) break;
        EUDBreak()
        # (Line 78) case 100:
    _t14 = EUDSwitchCase()
    # (Line 79) x += 5;
    if _t14(100):
        x.__iadd__(5)
        # (Line 80) break;
        EUDBreak()
        # (Line 81) case 112:
    _t15 = EUDSwitchCase()
    # (Line 82) x += 8;
    if _t15(112):
        x.__iadd__(8)
        # (Line 83) break;
        EUDBreak()
        # (Line 84) case 116:
    _t16 = EUDSwitchCase()
    # (Line 85) x += 11;
    if _t16(116):
        x.__iadd__(11)
        # (Line 86) break;
        EUDBreak()
        # (Line 87) default:
    # (Line 88) x = 0;
    if EUDSwitchDefault()():
        x << (0)
        # (Line 89) }
    # (Line 90) ret[4] = x;  // 1258
    EUDEndSwitch()
    _ARRW(ret, 4) << (x)
    # (Line 93) switch (x, 511) {
    EUDSwitch(x, 511)
    # (Line 94) case 121:
    _t17 = EUDSwitchCase()
    # (Line 95) x += 1;
    if _t17(121):
        x.__iadd__(1)
        # (Line 96) break;
        EUDBreak()
        # (Line 97) case 179:
    _t18 = EUDSwitchCase()
    # (Line 98) x += 4;
    if _t18(179):
        x.__iadd__(4)
        # (Line 99) break;
        EUDBreak()
        # (Line 100) case 234:  // OK
    _t19 = EUDSwitchCase()
    # (Line 101) x += 2;
    if _t19(234):
        x.__iadd__(2)
        # (Line 102) break;
        EUDBreak()
        # (Line 103) case 338:
    _t20 = EUDSwitchCase()
    # (Line 104) x += 8;
    if _t20(338):
        x.__iadd__(8)
        # (Line 105) break;
        EUDBreak()
        # (Line 106) case 428:
    _t21 = EUDSwitchCase()
    # (Line 107) x += 5;
    if _t21(428):
        x.__iadd__(5)
        # (Line 108) break;
        EUDBreak()
        # (Line 109) case 453:
    _t22 = EUDSwitchCase()
    # (Line 110) x += 7;
    if _t22(453):
        x.__iadd__(7)
        # (Line 111) break;
        EUDBreak()
        # (Line 112) default:
    # (Line 113) x = 0;
    if EUDSwitchDefault()():
        x << (0)
        # (Line 114) }
    # (Line 115) ret[5] = x;  // 1260
    EUDEndSwitch()
    _ARRW(ret, 5) << (x)
    # (Line 116) return ret;
    EUDReturn(ret)
    # (Line 117) }
    # (Line 119) const ack = PVariable(list(1, 2, 3, 4, 5, 6, 7, 8));

ack = _CGFW(lambda: [PVariable(FlattenList([1, 2, 3, 4, 5, 6, 7, 8]))], 1)[0]
# (Line 120) const ackMax = 8;
ackMax = _CGFW(lambda: [8], 1)[0]
# (Line 121) function test_array() {
@EUDFunc
def f_test_array():
    # (Line 122) var ret = 0;
    ret = _TYLV([None], [0])
    # (Line 123) const p = EUDVariable(1);
    p = EUDVariable(1)
    # (Line 124) ret += ack[p] % ackMax > 4 ? 1 : 2;  // ret = 2
    ret.__iadd__(EUDTernary(ack[p] % ackMax <= 4, neg=True)(1)(2))
    # (Line 126) const arr = [1, 2, 3, 4, 5, 6, 7, 8];
    arr = _ARR(FlattenList([1, 2, 3, 4, 5, 6, 7, 8]))
    # (Line 127) ack[0] %= arr[p];
    _ARRW(ack, 0).__imod__(arr[p])
    # (Line 128) ret = ret >> 0;  // ret = 2
    ret << (ret >> 0)
    # (Line 130) ack[p] &= 1;  // ack[1] = 0
    _ARRW(ack, p).__iand__(1)
    # (Line 131) ack[p] &= arr[p];
    _ARRW(ack, p).__iand__(arr[p])
    # (Line 132) ack[p] -= -2;  // ack[1] = 2
    _ARRW(ack, p).__isub__(-2)
    # (Line 133) const x = ack[p];
    x = ack[p]
    # (Line 134) ack[p] = x & arr[p];  // 2 & 2
    _ARRW(ack, p) << (x & arr[p])
    # (Line 135) arr[p] &= ack[p];
    _ARRW(arr, p).__iand__(ack[p])
    # (Line 136) ret *= ack[p] * arr[p];  // ret = 8
    ret.__imul__(ack[p] * arr[p])
    # (Line 138) arr[p] ^= ack[p];  // arr[1] = 0
    _ARRW(arr, p).__ixor__(ack[p])
    # (Line 139) arr[p] |= ack[0];  // arr[1] = 1
    _ARRW(arr, p).__ior__(ack[0])
    # (Line 140) arr[p] <<= ack[p];  // arr[1] = 4
    _ARRW(arr, p).__ilshift__(ack[p])
    # (Line 141) ret |= arr[p];  // ret = 12
    ret.__ior__(arr[p])
    # (Line 143) if (ack[p] > arr[p]) ret = 0;
    if EUDIf()(_ARRC(ack, p) <= arr[p], neg=True):
        ret << (0)
        # (Line 144) if (arr[p]) ret <<= 1;  // ret = 24
    EUDEndIf()
    if EUDIf()(arr[p]):
        ret.__ilshift__(1)
        # (Line 145) ret -= ack[p] + p / 2;  // ret = 22
    EUDEndIf()
    ret.__isub__(ack[p] + p // 2)
    # (Line 147) switch(arr[p]) {
    EUDSwitch(arr[p])
    # (Line 148) case 4:  // fall-through
    _t3 = EUDSwitchCase()
    # (Line 149) case 1:
    if _t3(4):
        pass
    _t4 = EUDSwitchCase()
    # (Line 150) ret += 1;  // ret = 23
    if _t4(1):
        ret.__iadd__(1)
        # (Line 151) }
    # (Line 152) switch(ack[p]) {
    EUDEndSwitch()
    EUDSwitch(ack[p])
    # (Line 153) case 2:
    _t5 = EUDSwitchCase()
    # (Line 154) break;
    if _t5(2):
        EUDBreak()
        # (Line 155) default:
    # (Line 156) ret = 0;
    if EUDSwitchDefault()():
        ret << (0)
        # (Line 157) }
    # (Line 159) return ret;  // ret = 23
    EUDEndSwitch()
    EUDReturn(ret)
    # (Line 160) }
    # (Line 162) function test_all_actions() {

@EUDFunc
def f_test_all_actions():
    # (Line 163) var sound = $T("sound\\Misc\\PError.WAV");
    sound = _TYLV([None], [GetStringIndex("sound\\Misc\\PError.WAV")])
    # (Line 164) PlayWAVAll(sound);
    # (Line 165) }
    _ALL(PlayWAVAll(sound))
