#!/usr/bin/python
# Copyright 2023 by Armoha.
# All rights reserved.
# This file is part of EUD python library (eudplib),
# and is released under "MIT License Agreement". Please see the LICENSE
# file that should have been included as part of this package.

def alloc_objects(dwoccupmap_list: dict) -> tuple[list[int], int]: ...

class ObjAllocator:
    def WriteByte(self, number: int): ...
    def WriteWord(self, number: int): ...
    def WriteDword(self, number): ...
    def WritePack(self, structformat: str, _arglist: list): ...
    def WriteBytes(self, b: bytes): ...
    def WriteSpace(self, ssize: int): ...

class ConstExpr:
    def __init__(
        self, baseobj: "ConstExpr | None", offset: int, rlocmode: int
    ) -> None: ...
