#!/usr/bin/python
# Copyright 2023 by Armoha.
# All rights reserved.
# This file is part of EUD python library (eudplib),
# and is released under "MIT License Agreement". Please see the LICENSE
# file that should have been included as part of this package.

from .allocator import ConstExpr, RlocInt_C

class EUDObject(ConstExpr):
    def __new__(cls, *args, **kwargs) -> EUDObject: ...
    def __init__(self) -> None: ...
    def DynamicConstructed(self) -> bool: ...
    def Evaluate(self) -> RlocInt_C: ...
    def GetDataSize(self) -> int: ...
    def CollectDependency(self, pbuf) -> None: ...
    def WritePayload(self, pbuf) -> None: ...
