#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
Copyright (c) 2014 trgk

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""


from .localize import *

oldGlobals = set(globals().keys())

from .utils import *
from .core import *
from .trigger import *
from .ctrlstru import *
from .eudlib import *
from .epscript import *
from .trigtrg.runtrigtrg import (
    RunTrigTrigger,
    GetFirstTrigTrigger,
    GetLastTrigTrigger,
    TrigTriggerBegin,
    TrigTriggerEnd,
)

from .maprw import *


__version__ = "0.67.3"

import types

# remove modules from __all__

_alllist = []
for _k, _v in dict(globals()).items():
    if _k in oldGlobals:
        continue
    elif _k != "stocktrg" and isinstance(_v, types.ModuleType):
        continue
    elif _k[0] == "_":
        continue
    _alllist.append(_k)


del _k
del _v


def eudplibVersion():
    return __version__


__all__ = [
    oldGlobals,
    u2b,
    b2u,
    u2utf8,
    b2i1,
    b2i2,
    b2i4,
    i2b1,
    i2b2,
    i2b4,
    EUDCreateBlock,
    EUDGetLastBlock,
    EUDGetLastBlockOfName,
    EUDPeekBlock,
    EUDPopBlock,
    EUDGetBlockList,
    EPD,
    FlattenList,
    List2Assignable,
    Assignable2List,
    SCMD2Text,
    cachedfunc,
    isStrict,
    setStrict,
    RandList,
    EPError,
    EPWarning,
    ep_assert,
    ep_eprint,
    ep_warn,
    ExprProxy,
    unProxy,
    isUnproxyInstance,
    find_data_file,
    ConstExpr,
    Forward,
    Evaluate,
    IsConstExpr,
    RlocInt,
    RlocInt_C,
    toRlocInt,
    GetObjectAddr,
    CreatePayload,
    CompressPayload,
    RegisterCreatePayloadCallback,
    EUDObject,
    Db,
    Disabled,
    RawTrigger,
    GetTriggerCounter,
    PushTriggerScope,
    PopTriggerScope,
    NextTrigger,
    SetNextTrigger,
    Condition,
    Action,
    CountdownTimer,
    Command,
    Bring,
    Accumulate,
    Kills,
    CommandMost,
    CommandMostAt,
    MostKills,
    HighestScore,
    MostResources,
    Switch,
    ElapsedTime,
    Opponents,
    Deaths,
    CommandLeast,
    CommandLeastAt,
    LeastKills,
    LowestScore,
    LeastResources,
    Score,
    Always,
    Never,
    Memory,
    MemoryEPD,
    DeathsX,
    MemoryX,
    MemoryXEPD,
    Victory,
    Defeat,
    PreserveTrigger,
    Wait,
    PauseGame,
    UnpauseGame,
    Transmission,
    PlayWAV,
    DisplayText,
    CenterView,
    CreateUnitWithProperties,
    SetMissionObjectives,
    SetSwitch,
    SetCountdownTimer,
    RunAIScript,
    RunAIScriptAt,
    LeaderBoardControl,
    LeaderBoardControlAt,
    LeaderBoardResources,
    LeaderBoardKills,
    LeaderBoardScore,
    KillUnit,
    KillUnitAt,
    RemoveUnit,
    RemoveUnitAt,
    SetResources,
    SetScore,
    MinimapPing,
    TalkingPortrait,
    MuteUnitSpeech,
    UnMuteUnitSpeech,
    LeaderBoardComputerPlayers,
    LeaderBoardGoalControl,
    LeaderBoardGoalControlAt,
    LeaderBoardGoalResources,
    LeaderBoardGoalKills,
    LeaderBoardGoalScore,
    MoveLocation,
    MoveUnit,
    LeaderBoardGreed,
    SetNextScenario,
    SetDoodadState,
    SetInvincibility,
    CreateUnit,
    SetDeaths,
    Order,
    Comment,
    GiveUnits,
    ModifyUnitHitPoints,
    ModifyUnitEnergy,
    ModifyUnitShields,
    ModifyUnitResourceAmount,
    ModifyUnitHangarCount,
    PauseTimer,
    UnpauseTimer,
    Draw,
    SetAllianceStatus,
    SetMemory,
    SetNextPtr,
    SetMemoryEPD,
    SetDeathsX,
    SetMemoryX,
    SetMemoryXEPD,
    SetKills,
    All,
    Enemy,
    Ally,
    AlliedVictory,
    AtLeast,
    AtMost,
    Exactly,
    SetTo,
    Add,
    Subtract,
    Move,
    Patrol,
    Attack,
    P1,
    P2,
    P3,
    P4,
    P5,
    P6,
    P7,
    P8,
    P9,
    P10,
    P11,
    P12,
    Player1,
    Player2,
    Player3,
    Player4,
    Player5,
    Player6,
    Player7,
    Player8,
    Player9,
    Player10,
    Player11,
    Player12,
    CurrentPlayer,
    Foes,
    Allies,
    NeutralPlayers,
    AllPlayers,
    Force1,
    Force2,
    Force3,
    Force4,
    NonAlliedVictoryPlayers,
    Enable,
    Disable,
    Toggle,
    Ore,
    Gas,
    OreAndGas,
    Total,
    Units,
    Buildings,
    UnitsAndBuildings,
    Razings,
    KillsAndRazings,
    Custom,
    Set,
    Clear,
    Random,
    Cleared,
    EncodeAllyStatus,
    EncodeComparison,
    EncodeCount,
    EncodeModifier,
    EncodeOrder,
    EncodePlayer,
    EncodeProperty,
    EncodePropState,
    EncodeResource,
    EncodeScore,
    EncodeSwitchAction,
    EncodeSwitchState,
    EncodeAIScript,
    EncodeLocation,
    EncodeString,
    EncodeSwitch,
    EncodeUnit,
    EncodeTBL,
    GetLocationIndex,
    GetStringIndex,
    GetSwitchIndex,
    GetUnitIndex,
    GetPropertyIndex,
    UnitProperty,
    IsMapdataInitalized,
    GetChkTokenized,
    TBL,
    GetPlayerInfo,
    EUDVariable,
    VProc,
    IsEUDVariable,
    EUDCreateVariables,
    SeqCompute,
    NonSeqCompute,
    SetVariables,
    EP_SetRValueStrictMode,
    EUDLightVariable,
    EUDLightBool,
    EUDXVariable,
    EUDVArray,
    selftype,
    EUDStruct,
    EUDFunc,
    EUDTracedFunc,
    EUDTypedFunc,
    EUDTracedTypedFunc,
    EUDXTypedFunc,
    EUDFullFunc,
    EUDFuncPtr,
    EUDTypedFuncPtr,
    EUDMethod,
    EUDTracedMethod,
    EUDTypedMethod,
    EUDTracedTypedMethod,
    EUDReturn,
    EUDFuncN,
    EUDTraceLog,
    GetTraceStackDepth,
    createEncoder,
    TrgAllyStatus,
    TrgComparison,
    TrgCount,
    TrgModifier,
    TrgOrder,
    TrgPlayer,
    TrgProperty,
    TrgPropState,
    TrgResource,
    TrgScore,
    TrgSwitchAction,
    TrgSwitchState,
    TrgAIScript,
    TrgLocation,
    TrgString,
    TrgSwitch,
    TrgUnit,
    TrgTBL,
    f_bitand,
    f_bitor,
    f_bitxor,
    f_bitnand,
    f_bitnor,
    f_bitnxor,
    f_bitnot,
    f_bitlshift,
    f_bitrshift,
    f_bitsplit,
    f_mul,
    f_div,
    EUDClearNamespace,
    EUDRegisterObjectToNamespace,
    EUDRegistered,
    GetEUDNamespace,
    SetCurrentPlayer,
    AddCurrentPlayer,
    Trigger,
    EUDBranch,
    PTrigger,
    CtrlStruOpener,
    DoActions,
    EUDJump,
    EUDJumpIf,
    EUDJumpIfNot,
    EUDTernary,
    EUDIf,
    EUDIfNot,
    EUDElseIf,
    EUDElseIfNot,
    EUDElse,
    EUDEndIf,
    EUDExecuteOnce,
    EUDEndExecuteOnce,
    EUDInfLoop,
    EUDEndInfLoop,
    EUDLoopN,
    EUDEndLoopN,
    EUDLoopRange,
    EUDWhile,
    EUDWhileNot,
    EUDEndWhile,
    EUDSwitch,
    EUDSwitchCase,
    EUDSwitchDefault,
    EUDEndSwitch,
    EUDContinue,
    EUDContinueIf,
    EUDContinueIfNot,
    EUDSetContinuePoint,
    EUDIsContinuePointSet,
    EUDBreak,
    EUDBreakIf,
    EUDBreakIfNot,
    EUDSCOr,
    EUDSCAnd,
    f_setloc,
    f_addloc,
    f_dilateloc,
    f_getlocTL,
    f_setloc_epd,
    f_setcurpl,
    f_addcurpl,
    f_getcurpl,
    f_setcurpl2cpcache,
    f_wwrite_epd,
    f_bwrite_epd,
    f_wread_epd,
    f_bread_epd,
    f_dwepdread_epd,
    f_dwread_epd,
    f_epdread_epd,
    f_flagread_epd,
    f_dwwrite_epd,
    f_dwadd_epd,
    f_dwsubtract_epd,
    f_dwbreak,
    f_dwbreak2,
    f_dwepdread_epd_safe,
    f_dwread_epd_safe,
    f_epdread_epd_safe,
    f_dwepdread_cp,
    f_dwread_cp,
    f_epdread_cp,
    f_wread_cp,
    f_bread_cp,
    f_dwwrite_cp,
    f_dwadd_cp,
    f_dwsubtract_cp,
    f_wwrite_cp,
    f_bwrite_cp,
    EUDByteReader,
    EUDByteWriter,
    EUDByteStream,
    CPByteWriter,
    f_dwwrite,
    f_wwrite,
    f_bwrite,
    f_dwread,
    f_wread,
    f_bread,
    f_repmovsd_epd,
    f_memcpy,
    f_memcmp,
    f_readgen_epd,
    f_readgen_cp,
    f_cunitread_epd,
    f_cunitread_cp,
    f_cunitepdread_epd,
    f_cunitepdread_cp,
    f_maskread_epd,
    f_maskread_cp,
    f_posread_epd,
    f_posread_cp,
    EUDVArrayReader,
    GetMapStringAddr,
    CPString,
    DBString,
    f_parse,
    f_sprintf,
    f_sprintf_cp,
    f_eprintf,
    f_eprintAll,
    StringBuffer,
    DisplayTextAt,
    GetGlobalStringBuffer,
    f_simpleprint,
    f_println,
    f_printAt,
    f_printAll,
    f_printAllAt,
    f_strcpy,
    f_strcmp,
    f_strlen,
    f_strlen_epd,
    f_strnstr,
    f_dbstr_adddw,
    f_dbstr_addptr,
    f_dbstr_addstr,
    f_dbstr_addstr_epd,
    ptr2s,
    epd2s,
    hptr,
    f_dbstr_print,
    f_cpstr_adddw,
    f_cpstr_addptr,
    PColor,
    PName,
    f_cpstr_print,
    f_raise_CCMU,
    GetTBLAddr,
    f_eprintln,
    f_eprintln2,
    FixedText,
    f_gettextptr,
    f_cp949_to_utf8_cpy,
    SetPName,
    SetPNamef,
    IsPName,
    f_settbl,
    f_settbl2,
    f_settblf,
    f_settblf2,
    f_cpchar_adddw,
    f_cpchar_print,
    TextFX_FadeIn,
    TextFX_FadeOut,
    TextFX_SetTimer,
    TextFX_Remove,
    EUDAnd,
    EUDOr,
    EUDNot,
    f_getuserplayerid,
    IsUserCP,
    f_getgametick,
    f_getseed,
    f_srand,
    f_rand,
    f_dwrand,
    f_randomize,
    f_dwpatch_epd,
    f_blockpatch_epd,
    f_unpatchall,
    f_playerexist,
    EUDLoopPlayer,
    EUDPlayerLoop,
    EUDEndPlayerLoop,
    EUDLoopList,
    EUDLoopUnit,
    EUDLoopUnit2,
    EUDLoopNewUnit,
    EUDLoopPlayerUnit,
    EUDLoopSprite,
    EUDLoopBullet,
    EUDLoopTrigger,
    EUDBinaryMin,
    EUDBinaryMax,
    QueueGameCommand,
    QueueGameCommand_RightClick,
    QueueGameCommand_QueuedRightClick,
    QueueGameCommand_Select,
    QueueGameCommand_MinimapPing,
    QueueGameCommand_PauseGame,
    QueueGameCommand_ResumeGame,
    QueueGameCommand_RestartGame,
    QueueGameCommand_UseCheat,
    QueueGameCommand_TrainUnit,
    QueueGameCommand_MergeDarkArchon,
    QueueGameCommand_MergeArchon,
    f_lengthdir,
    f_atan2,
    f_sqrt,
    EUDArray,
    EUDGrp,
    EUDStack,
    EPDOffsetMap,
    EPDCUnitMap,
    PVariable,
    epsCompile,
    EPS_SetDebug,
    EPSFinder,
    EPSLoader,
    IsSCDBMap,
    RunTrigTrigger,
    GetFirstTrigTrigger,
    GetLastTrigTrigger,
    TrigTriggerBegin,
    TrigTriggerEnd,
    LoadMap,
    SaveMap,
    EUDDoEvents,
    EUDOnStart,
    MPQAddFile,
    MPQAddWave,
    MPQCheckFile,
    PRT_SetInliningRate,
    PRT_SkipPayloadRelocator,
    eudplibVersion,
]


from .epscript.epscompile import setEpsGlobals

setEpsGlobals(_alllist)
