#!/usr/bin/env python3
# Copyright 2026 by Armoha.
# All rights reserved.
# This file is part of EUD python library (eudplib),
# and is released under "MIT License Agreement". Please see the LICENSE
# file that should have been included as part of this package.

"""Build the epScript compiler shared library for the current platform.

Builds ``libepScriptLib.{so,dll,dylib}`` from ``src/epscript`` with CMake and
copies it to ``src/eudplib/epscript/`` so that
``eudplib.epscript.epscompile`` can load it.

The parser (``parser/epparser.cpp``) is generated by ``lemon2`` at build time:
``lemon2.exe`` is committed for Windows, while on Linux/macOS ``lemon2`` is
compiled from ``lemon2.c`` first.
"""

import platform
import shutil
import subprocess
import sys
from pathlib import Path

SRC = Path(__file__).resolve().parent  # src/epscript
DEST = SRC.parent / "eudplib" / "epscript"  # src/eudplib/epscript
BUILD = SRC / "cmake-build"

_LIB_NAMES = {
    "Windows": "libepScriptLib.dll",
    "Linux": "libepScriptLib.so",
    "Darwin": "libepScriptLib.dylib",
}


def _run(cmd, cwd=SRC) -> None:
    print("+", " ".join(str(c) for c in cmd))
    subprocess.run(cmd, cwd=cwd, check=True)


def _build_lemon2() -> None:
    """Ensure the lemon2 parser generator is available at src/epscript/lemon2."""
    if platform.system() == "Windows":
        if not (SRC / "lemon2.exe").exists():
            raise RuntimeError("lemon2.exe is missing; clone the repo with "
                               "--recursive")
        return
    cc = shutil.which("cc") or shutil.which("gcc") or shutil.which("clang")
    if cc is None:
        raise RuntimeError("No C compiler found (cc/gcc/clang) to build lemon2")
    _run([
        cc, "-std=gnu89", "-O2", "-o", str(SRC / "lemon2"), str(SRC / "lemon2.c")
    ])


def _build_epscript_lib() -> None:
    _run([
        "cmake", "-S", str(SRC), "-B", str(BUILD),
        "-DCMAKE_BUILD_TYPE=Release", "-DBUILD_PYEPSCRIPT=OFF",
    ])
    _run([
        "cmake", "--build", str(BUILD), "--target", "epScriptLib", "--config",
        "Release",
    ])


def _install_lib() -> None:
    libname = _LIB_NAMES[platform.system()]
    candidates = [BUILD / libname, BUILD / "Release" / libname]
    src_lib = next((p for p in candidates if p.exists()), None)
    if src_lib is None:
        raise RuntimeError(
            f"Could not find the built library {libname} under {BUILD}")
    DEST.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src_lib, DEST / libname)
    print(f"Installed {DEST / libname}")


def main() -> None:
    if platform.system() not in _LIB_NAMES:
        sys.exit(f"Unsupported platform: {platform.system()}")
    _build_lemon2()
    _build_epscript_lib()
    _install_lib()


if __name__ == "__main__":
    main()
