//===========================================================================
// 
// Small Wars
// 
//   Warcraft III map script
//   Generated by the Warcraft III World Editor
//   Date: Thu Apr 29 20:03:59 2010
//   Map Author: Rorslae
// 
//===========================================================================

//***************************************************************************
//*
//*  Global Variables
//*
//***************************************************************************

globals
endglobals

function InitGlobals takes nothing returns nothing
endfunction

//***************************************************************************
//*
//*  Unit Creation
//*
//***************************************************************************

//===========================================================================
function CreateBuildingsForPlayer0 takes nothing returns nothing
    local player p = Player(0)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'hgtw', -1408.0, 832.0, 270.000 )
    set u = CreateUnit( p, 'hgtw', 1344.0, 704.0, 270.000 )
    set u = CreateUnit( p, 'hbar', -192.0, 1216.0, 270.000 )
    set u = CreateUnit( p, 'hars', 192.0, 1216.0, 270.000 )
    set u = CreateUnit( p, 'hgra', 576.0, 1216.0, 270.000 )
    set u = CreateUnit( p, 'hhou', 1152.0, 1088.0, 270.000 )
    set u = CreateUnit( p, 'hhou', 1280.0, 1088.0, 270.000 )
    set u = CreateUnit( p, 'hhou', 1152.0, 1216.0, 270.000 )
    set u = CreateUnit( p, 'hhou', 1280.0, 1216.0, 270.000 )
    set u = CreateUnit( p, 'hhou', 1024.0, 1216.0, 270.000 )
    set u = CreateUnit( p, 'hhou', 1280.0, 960.0, 270.000 )
    set u = CreateUnit( p, 'hhou', 1024.0, 960.0, 270.000 )
    set u = CreateUnit( p, 'hgtw', -960.0, -64.0, 270.000 )
    set u = CreateUnit( p, 'hgtw', 960.0, -64.0, 270.000 )
    set u = CreateUnit( p, 'hbla', -192.0, 832.0, 270.000 )
    set u = CreateUnit( p, 'hhou', 1024.0, 1088.0, 270.000 )
    set u = CreateUnit( p, 'htow', -1664.0, 1152.0, 270.000 )
    set u = CreateUnit( p, 'hlum', 160.0, 864.0, 270.000 )
    set u = CreateUnit( p, 'halt', 544.0, 864.0, 270.000 )
    set u = CreateUnit( p, 'harm', 896.0, 704.0, 270.000 )
    set u = CreateUnit( p, 'hgtw', -64.0, 320.0, 270.000 )
    set u = CreateUnit( p, 'hgtw', 64.0, 320.0, 270.000 )
endfunction

//===========================================================================
function CreateUnitsForPlayer0 takes nothing returns nothing
    local player p = Player(0)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'hkni', -816.7, -59.8, 270.000 )
    set u = CreateUnit( p, 'hkni', -699.5, -69.7, 270.000 )
    set u = CreateUnit( p, 'hkni', -571.2, -74.7, 270.000 )
    set u = CreateUnit( p, 'hkni', -443.4, -69.7, 270.000 )
    set u = CreateUnit( p, 'hkni', -310.3, -77.1, 270.000 )
    set u = CreateUnit( p, 'hkni', -189.8, -79.6, 270.000 )
    set u = CreateUnit( p, 'hkni', -48.5, -82.1, 270.000 )
    set u = CreateUnit( p, 'hkni', 70.5, -69.7, 270.000 )
    set u = CreateUnit( p, 'hkni', 196.3, -72.2, 270.000 )
    set u = CreateUnit( p, 'hkni', 322.9, -69.3, 270.000 )
    set u = CreateUnit( p, 'hkni', 461.4, -74.3, 270.000 )
    set u = CreateUnit( p, 'hkni', 557.8, -76.7, 270.000 )
    set u = CreateUnit( p, 'hkni', 695.3, -74.3, 270.000 )
    set u = CreateUnit( p, 'hkni', 829.0, -66.1, 270.000 )
    set u = CreateUnit( p, 'hrif', 841.4, 64.5, 270.000 )
    set u = CreateUnit( p, 'hrif', 716.5, 64.5, 270.000 )
    set u = CreateUnit( p, 'hrif', 578.6, 73.4, 270.000 )
    set u = CreateUnit( p, 'hrif', 436.6, 73.4, 270.000 )
    set u = CreateUnit( p, 'hrif', 311.3, 73.4, 270.000 )
    set u = CreateUnit( p, 'hrif', 202.8, 73.4, 270.000 )
    set u = CreateUnit( p, 'hrif', 64.1, 73.4, 270.000 )
    set u = CreateUnit( p, 'hrif', -59.9, 75.7, 270.000 )
    set u = CreateUnit( p, 'hrif', -195.7, 67.6, 270.000 )
    set u = CreateUnit( p, 'hrif', -312.7, 71.6, 270.000 )
    set u = CreateUnit( p, 'hrif', -418.6, 71.6, 270.000 )
    set u = CreateUnit( p, 'hrif', -565.7, 63.6, 270.000 )
    set u = CreateUnit( p, 'hrif', -698.3, 67.7, 270.000 )
    set u = CreateUnit( p, 'hrif', -819.1, 61.9, 270.000 )
    set u = CreateUnit( p, 'Hpal', 51.6, -181.2, 270.000 )
    call SetUnitState( u, UNIT_STATE_MANA, 0 )
    set u = CreateUnit( p, 'Hblm', -72.1, 211.2, 270.000 )
    call SetUnitState( u, UNIT_STATE_MANA, 0 )
    set u = CreateUnit( p, 'Hmkg', -60.4, -194.9, 270.000 )
    call SetUnitState( u, UNIT_STATE_MANA, 0 )
    set u = CreateUnit( p, 'Hamg', 63.0, 189.8, 270.000 )
    call SetUnitState( u, UNIT_STATE_MANA, 0 )
    set u = CreateUnit( p, 'hgry', -139.9, 39.6, 311.230 )
    set u = CreateUnit( p, 'hgry', 119.3, 39.6, 87.443 )
    set u = CreateUnit( p, 'hpea', -1358.6, 1287.1, 90.420 )
    set u = CreateUnit( p, 'hpea', -1356.6, 1204.5, 358.286 )
    set u = CreateUnit( p, 'hpea', -1355.7, 1105.9, 112.119 )
    set u = CreateUnit( p, 'hpea', -1350.4, 1003.3, 257.363 )
endfunction

//===========================================================================
function CreateBuildingsForPlayer1 takes nothing returns nothing
    local player p = Player(1)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'eaow', -832.0, -1664.0, 270.000 )
    set u = CreateUnit( p, 'eaoe', -384.0, -1664.0, 270.000 )
    set u = CreateUnit( p, 'eaom', 64.0, -1664.0, 270.000 )
    set u = CreateUnit( p, 'etrp', -992.0, -480.0, 270.000 )
    set u = CreateUnit( p, 'etrp', 992.0, -480.0, 270.000 )
    set u = CreateUnit( p, 'emow', -1120.0, -1696.0, 270.000 )
    set u = CreateUnit( p, 'emow', -1120.0, -1504.0, 270.000 )
    set u = CreateUnit( p, 'emow', -1504.0, -1312.0, 270.000 )
    set u = CreateUnit( p, 'emow', -1312.0, -1696.0, 270.000 )
    set u = CreateUnit( p, 'emow', -1504.0, -1504.0, 270.000 )
    set u = CreateUnit( p, 'emow', -1312.0, -1504.0, 270.000 )
    set u = CreateUnit( p, 'emow', -1120.0, -1312.0, 270.000 )
    set u = CreateUnit( p, 'emow', -1504.0, -1696.0, 270.000 )
    set u = CreateUnit( p, 'etol', 1280.0, -1664.0, 270.000 )
    set u = CreateUnit( p, 'edob', -832.0, -1344.0, 270.000 )
    set u = CreateUnit( p, 'edos', -384.0, -1280.0, 270.000 )
    set u = CreateUnit( p, 'eate', 96.0, -1248.0, 270.000 )
    set u = CreateUnit( p, 'etrp', 1440.0, -1312.0, 270.000 )
    set u = CreateUnit( p, 'etrp', -1440.0, -1056.0, 270.000 )
    set u = CreateUnit( p, 'etrp', -96.0, -864.0, 270.000 )
    set u = CreateUnit( p, 'etrp', 96.0, -864.0, 270.000 )
endfunction

//===========================================================================
function CreateUnitsForPlayer1 takes nothing returns nothing
    local player p = Player(1)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'esen', -807.3, -482.7, 90.000 )
    set u = CreateUnit( p, 'esen', -695.8, -482.7, 90.000 )
    set u = CreateUnit( p, 'esen', -554.1, -492.0, 90.000 )
    set u = CreateUnit( p, 'esen', -428.1, -488.3, 90.000 )
    set u = CreateUnit( p, 'esen', -309.2, -488.3, 90.000 )
    set u = CreateUnit( p, 'esen', -170.4, -484.5, 90.000 )
    set u = CreateUnit( p, 'esen', -49.8, -484.5, 90.000 )
    set u = CreateUnit( p, 'esen', 76.9, -497.6, 90.000 )
    set u = CreateUnit( p, 'esen', 217.6, -492.0, 90.000 )
    set u = CreateUnit( p, 'esen', 350.4, -481.5, 90.000 )
    set u = CreateUnit( p, 'esen', 468.8, -500.4, 90.000 )
    set u = CreateUnit( p, 'esen', 577.4, -489.1, 90.000 )
    set u = CreateUnit( p, 'esen', 704.8, -506.1, 90.000 )
    set u = CreateUnit( p, 'esen', 836.2, -478.0, 90.000 )
    set u = CreateUnit( p, 'earc', -822.2, -622.5, 90.000 )
    set u = CreateUnit( p, 'earc', -690.4, -622.5, 90.000 )
    set u = CreateUnit( p, 'earc', -556.6, -627.8, 90.000 )
    set u = CreateUnit( p, 'earc', -435.8, -620.7, 90.000 )
    set u = CreateUnit( p, 'earc', -311.4, -611.9, 90.000 )
    set u = CreateUnit( p, 'earc', -180.5, -610.1, 90.000 )
    set u = CreateUnit( p, 'earc', -82.3, -610.1, 90.000 )
    set u = CreateUnit( p, 'earc', 57.6, -610.1, 90.000 )
    set u = CreateUnit( p, 'earc', 212.0, -611.9, 90.000 )
    set u = CreateUnit( p, 'earc', 341.8, -607.7, 90.000 )
    set u = CreateUnit( p, 'earc', 464.6, -616.7, 90.000 )
    set u = CreateUnit( p, 'earc', 589.9, -616.7, 90.000 )
    set u = CreateUnit( p, 'earc', 697.1, -618.5, 90.000 )
    set u = CreateUnit( p, 'earc', 822.4, -618.2, 90.000 )
    set u = CreateUnit( p, 'Edem', 80.6, -363.8, 90.000 )
    call SetUnitState( u, UNIT_STATE_MANA, 0 )
    set u = CreateUnit( p, 'Ewar', -54.5, -355.9, 90.000 )
    call SetUnitState( u, UNIT_STATE_MANA, 0 )
    set u = CreateUnit( p, 'Emoo', 82.9, -724.8, 90.000 )
    call SetUnitState( u, UNIT_STATE_MANA, 0 )
    set u = CreateUnit( p, 'Ekee', -48.4, -734.4, 90.000 )
    call SetUnitState( u, UNIT_STATE_MANA, 0 )
    set u = CreateUnit( p, 'ewsp', 916.2, -1796.1, 76.127 )
    set u = CreateUnit( p, 'ewsp', 936.5, -1689.6, 206.967 )
    set u = CreateUnit( p, 'ewsp', 923.8, -1564.5, 222.842 )
    set u = CreateUnit( p, 'ewsp', 823.2, -1598.5, 256.231 )
    set u = CreateUnit( p, 'ewsp', 817.2, -1698.0, 198.870 )
    set u = CreateUnit( p, 'ewsp', 817.9, -1798.5, 89.739 )
    set u = CreateUnit( p, 'ehpr', -242.5, -531.3, 193.948 )
    set u = CreateUnit( p, 'ehpr', -21.6, -529.6, 340.543 )
    set u = CreateUnit( p, 'ehpr', 198.0, -549.6, 254.045 )
endfunction

//===========================================================================
function CreateNeutralPassiveBuildings takes nothing returns nothing
    local player p = Player(PLAYER_NEUTRAL_PASSIVE)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'ngol', 512.0, -1664.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'ngol', -640.0, 1152.0, 270.000 )
    call SetResourceAmount( u, 12500 )
endfunction

//===========================================================================
function CreatePlayerBuildings takes nothing returns nothing
    call CreateBuildingsForPlayer0(  )
    call CreateBuildingsForPlayer1(  )
endfunction

//===========================================================================
function CreatePlayerUnits takes nothing returns nothing
    call CreateUnitsForPlayer0(  )
    call CreateUnitsForPlayer1(  )
endfunction

//===========================================================================
function CreateAllUnits takes nothing returns nothing
    call CreateNeutralPassiveBuildings(  )
    call CreatePlayerBuildings(  )
    call CreatePlayerUnits(  )
endfunction

//***************************************************************************
//*
//*  Players
//*
//***************************************************************************

function InitCustomPlayerSlots takes nothing returns nothing

    // Player 0
    call SetPlayerStartLocation( Player(0), 0 )
    call ForcePlayerStartLocation( Player(0), 0 )
    call SetPlayerColor( Player(0), ConvertPlayerColor(0) )
    call SetPlayerRacePreference( Player(0), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(0), true )
    call SetPlayerController( Player(0), MAP_CONTROL_USER )

    // Player 1
    call SetPlayerStartLocation( Player(1), 1 )
    call ForcePlayerStartLocation( Player(1), 1 )
    call SetPlayerColor( Player(1), ConvertPlayerColor(1) )
    call SetPlayerRacePreference( Player(1), RACE_PREF_NIGHTELF )
    call SetPlayerRaceSelectable( Player(1), true )
    call SetPlayerController( Player(1), MAP_CONTROL_COMPUTER )

endfunction

function InitCustomTeams takes nothing returns nothing
    // Force: TRIGSTR_002
    call SetPlayerTeam( Player(0), 0 )
    call SetPlayerTeam( Player(1), 0 )

endfunction

//***************************************************************************
//*
//*  Main Initialization
//*
//***************************************************************************

//===========================================================================
function main takes nothing returns nothing
    call SetCameraBounds( -1920.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -1920.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 1920.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 1408.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -1920.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 1408.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 1920.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -1920.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM) )
    call SetDayNightModels( "Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl" )
    call NewSoundEnvironment( "Default" )
    call SetAmbientDaySound( "LordaeronSummerDay" )
    call SetAmbientNightSound( "LordaeronSummerNight" )
    call SetMapMusic( "Music", true, 0 )
    call CreateAllUnits(  )
    call InitBlizzard(  )
    call InitGlobals(  )

endfunction

//***************************************************************************
//*
//*  Map Configuration
//*
//***************************************************************************

function config takes nothing returns nothing
    call SetMapName( "TRIGSTR_004" )
    call SetMapDescription( "TRIGSTR_008" )
    call SetPlayers( 2 )
    call SetTeams( 2 )
    call SetGamePlacement( MAP_PLACEMENT_USE_MAP_SETTINGS )

    call DefineStartLocation( 0, -1664.0, 1152.0 )
    call DefineStartLocation( 1, 1280.0, -1664.0 )

    // Player setup
    call InitCustomPlayerSlots(  )
    call SetPlayerSlotAvailable( Player(0), MAP_CONTROL_USER )
    call SetPlayerSlotAvailable( Player(1), MAP_CONTROL_COMPUTER )
    call InitGenericPlayerSlots(  )
endfunction

