#define IFX                              1
#define ELSE                             2
#define ASSIGN                           3
#define QMARK                            4
#define COMMA                            5
#define LOR                              6
#define LAND                             7
#define LNOT                             8
#define EQ                               9
#define LE                              10
#define LT                              11
#define GE                              12
#define GT                              13
#define NE                              14
#define BITOR                           15
#define BITXOR                          16
#define BITAND                          17
#define LSHIFT                          18
#define RSHIFT                          19
#define PLUS                            20
#define MINUS                           21
#define DIVIDE                          22
#define MULTIPLY                        23
#define MOD                             24
#define UNARY                           25
#define BITNOT                          26
#define LPAREN                          27
#define LSQBRACKET                      28
#define PERIOD                          29
#define SEMICOLON                       30
#define IMPORT                          31
#define NAME                            32
#define TRGCONST                        33
#define AS                              34
#define COLON                           35
#define FUNCTION                        36
#define RPAREN                          37
#define OBJECT                          38
#define LBRACKET                        39
#define VAR                             40
#define RBRACKET                        41
#define NUMBER                          42
#define RSQBRACKET                      43
#define SUBSCRIPT                       44
#define KILLS                           45
#define MEMBER                          46
#define STRING                          47
#define FUNCCALL                        48
#define L2V                             49
#define MAPSTRING                       50
#define UNIT                            51
#define SWITCH                          52
#define LOCATION                        53
#define STATTXTTBL                      54
#define VARRAY                          55
#define LIST                            56
#define STATIC                          57
#define CONST                           58
#define INC                             59
#define DEC                             60
#define IADD                            61
#define ISUB                            62
#define IMUL                            63
#define IDIV                            64
#define IMOD                            65
#define ILSH                            66
#define IRSH                            67
#define IBND                            68
#define IBOR                            69
#define IBXR                            70
#define ONCE                            71
#define IF                              72
#define SWITCHCASE                      73
#define CASE                            74
#define DEFAULT                         75
#define WHILE                           76
#define FOR                             77
#define FOREACH                         78
#define CONTINUE                        79
#define BREAK                           80
#define RETURN                          81
#define CONDITIONNAME                   82
#define ACTIONNAME                      83
