#define IFX                              1
#define ELSE                             2
#define ASSIGN                           3
#define QMARK                            4
#define COMMA                            5
#define LOR                              6
#define LAND                             7
#define LNOT                             8
#define EQ                               9
#define LE                              10
#define LT                              11
#define GE                              12
#define GT                              13
#define NE                              14
#define BITOR                           15
#define BITXOR                          16
#define BITAND                          17
#define LSHIFT                          18
#define RSHIFT                          19
#define PLUS                            20
#define MINUS                           21
#define DIVIDE                          22
#define MULTIPLY                        23
#define MOD                             24
#define UNARY                           25
#define BITNOT                          26
#define LPAREN                          27
#define LSQBRACKET                      28
#define PERIOD                          29
#define SEMICOLON                       30
#define NAME                            31
#define IMPORT                          32
#define AS                              33
#define COLON                           34
#define FUNCTION                        35
#define RPAREN                          36
#define OBJECT                          37
#define LBRACKET                        38
#define VAR                             39
#define RBRACKET                        40
#define NUMBER                          41
#define RSQBRACKET                      42
#define SUBSCRIPT                       43
#define KILLS                           44
#define MEMBER                          45
#define STRING                          46
#define FUNCCALL                        47
#define L2V                             48
#define MAPSTRING                       49
#define UNIT                            50
#define SWITCH                          51
#define LOCATION                        52
#define VARRAY                          53
#define LIST                            54
#define STATIC                          55
#define CONST                           56
#define INC                             57
#define DEC                             58
#define IADD                            59
#define ISUB                            60
#define IMUL                            61
#define IDIV                            62
#define IMOD                            63
#define ILSH                            64
#define IRSH                            65
#define IBND                            66
#define IBOR                            67
#define IBXR                            68
#define ONCE                            69
#define IF                              70
#define SWITCHCASE                      71
#define CASE                            72
#define DEFAULT                         73
#define WHILE                           74
#define FOR                             75
#define FOREACH                         76
#define CONTINUE                        77
#define BREAK                           78
#define RETURN                          79
#define CONDITIONNAME                   80
#define ACTIONNAME                      81
